### ISSUE TITLE
Add Travis-CI integration

### ISSUE THREAD

**Issue by onwsk8r** [goption/golang-dockerfile#2]
```yaml
sudo: required

services:
  - docker
  
git:
  depth: 3

script:
  - docker build .

branches:
  only:
  - master
  - develop

notifications:
  email: false
```
